let a = 'hello';
let b = 1;
let c = '1';
console.log('a + b', a + b);
console.log('b + c', b + c);
console.log('typeof (b + c)', typeof (b + c));
console.log('b + c > 100', b + c > 100);
console.log('"11" > 100', '11' > 100);
console.log('"11" > "100"', '11' > '100');
console.log('a == b', a == b);
console.log('b == c', b == c);
console.log('b === c', b === c);
